/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.group5.paul_esys.components;

import java.awt.Window;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author nytri
 */
public class WindowBar extends javax.swing.JPanel {

	/**
	 * Creates new form WindowBar
	 */
	public WindowBar() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                lblMinimize = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                lblClose = new javax.swing.JLabel();

                setBackground(new java.awt.Color(119, 0, 0));
                setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

                lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minus.png"))); // NOI18N
                lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblMinimizeMouseClicked(evt);
                        }
                });
                add(lblMinimize);
                add(jLabel2);

                lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
                lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblCloseMouseClicked(evt);
                        }
                });
                add(lblClose);
        }// </editor-fold>//GEN-END:initComponents

        private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
		Window win = SwingUtilities.getWindowAncestor(this);
		win.dispose();
        }//GEN-LAST:event_lblCloseMouseClicked

        private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
		Window win = SwingUtilities.getWindowAncestor(this);
		((JFrame) win).setState(JFrame.ICONIFIED);
        }//GEN-LAST:event_lblMinimizeMouseClicked


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel lblClose;
        private javax.swing.JLabel lblMinimize;
        // End of variables declaration//GEN-END:variables
}
