package com.group5.paul_esys.screens.registrar.forms;

import com.group5.paul_esys.modules.registrar.model.Registrar;
import com.group5.paul_esys.modules.registrar.services.RegistrarService;
import com.group5.paul_esys.utils.FormValidationUtil;
import java.util.Optional;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nytri
 */
public class RegistrarForm extends javax.swing.JFrame {

  private static final java.util.logging.Logger logger =
    java.util.logging.Logger.getLogger(RegistrarForm.class.getName());
  private static final int MIN_EMPLOYEE_ID_LENGTH = 2;
  private static final int MAX_EMPLOYEE_ID_LENGTH = 30;
  private static final int MIN_NAME_LENGTH = 2;
  private static final int MAX_NAME_LENGTH = 50;
  private static final int MIN_CONTACT_LENGTH = 7;
  private static final int MAX_CONTACT_LENGTH = 20;
  private static final int MAX_EMAIL_LENGTH = 254;
  private static final int MIN_PASSWORD_LENGTH = 8;
  private static final int MAX_PASSWORD_LENGTH = 128;
  private static final Pattern EMPLOYEE_ID_PATTERN = Pattern.compile("^[A-Za-z0-9._\\-/]+$");
  private static final Pattern NAME_PATTERN = Pattern.compile("^[A-Za-z .'-]+$");
  private static final Pattern CONTACT_NUMBER_PATTERN = Pattern.compile("^[0-9+\\-\\s()]+$");
  private static final Pattern PASSWORD_PATTERN = Pattern.compile("^\\S+$");

  private final RegistrarService registrarService = RegistrarService.getInstance();
  private final Registrar editingRegistrar;
  private final Runnable onSavedCallback;

  public RegistrarForm() {
    this(null, null);
  }

  public RegistrarForm(Registrar editingRegistrar, Runnable onSavedCallback) {
    this.editingRegistrar = editingRegistrar;
    this.onSavedCallback = onSavedCallback;
    this.setUndecorated(true);
    initComponents();
    initializeFormState();
    this.setLocationRelativeTo(null);
  }

  private void initializeFormState() {
    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    windowBar1.setTitle("Registrar Account");

    if (editingRegistrar == null) {
      return;
    }

    jLabel1.setText("Update Registrar Account");
    btnSave.setText("Update");
    jLabel7.setText("New Password (Optional)");

    txtEmployeeId.setText(
      editingRegistrar.getEmployeeId() == null ? "" : editingRegistrar.getEmployeeId()
    );
    txtFirstName.setText(
      editingRegistrar.getFirstName() == null ? "" : editingRegistrar.getFirstName()
    );
    txtLastName.setText(
      editingRegistrar.getLastName() == null ? "" : editingRegistrar.getLastName()
    );
    txtContactNumber.setText(
      editingRegistrar.getContactNumber() == null ? "" : editingRegistrar.getContactNumber()
    );
    txtEmail.setText(
      registrarService
        .getUserEmailByUserId(editingRegistrar.getUserId())
        .orElse("")
    );

    txtPassword.setText("");
    txtConfirmPassword.setText("");
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                windowBar1 = new com.group5.paul_esys.components.WindowBar();
                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                txtEmployeeId = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                txtFirstName = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                txtLastName = new javax.swing.JTextField();
                jLabel5 = new javax.swing.JLabel();
                txtContactNumber = new javax.swing.JTextField();
                jLabel6 = new javax.swing.JLabel();
                txtEmail = new javax.swing.JTextField();
                jLabel7 = new javax.swing.JLabel();
                txtPassword = new javax.swing.JPasswordField();
                jLabel8 = new javax.swing.JLabel();
                txtConfirmPassword = new javax.swing.JPasswordField();
                btnSave = new javax.swing.JButton();
                btnCancel = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                windowBar1.setTitle("Registrar Account");

                jPanel1.setBackground(new java.awt.Color(255, 255, 255));

                jLabel1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
                jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel1.setText("Create Registrar Account");

                jLabel2.setText("Employee ID");

                txtEmployeeId.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());

                jLabel3.setText("First Name");

                txtFirstName.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());

                jLabel4.setText("Last Name");

                txtLastName.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());

                jLabel5.setText("Contact Number");

                txtContactNumber.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());

                jLabel6.setText("Email");

                txtEmail.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());

                jLabel7.setText("Password");

                txtPassword.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());

                jLabel8.setText("Confirm Password");

                txtConfirmPassword.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());

                btnSave.setBackground(new java.awt.Color(119, 0, 0));
                btnSave.setForeground(new java.awt.Color(255, 255, 255));
                btnSave.setText("Save");
                btnSave.addActionListener(this::btnSaveActionPerformed);

                btnCancel.setBackground(new java.awt.Color(119, 0, 0));
                btnCancel.setForeground(new java.awt.Color(255, 255, 255));
                btnCancel.setText("Cancel");
                btnCancel.addActionListener(this::btnCancelActionPerformed);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtEmployeeId)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtFirstName)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtLastName)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtContactNumber)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtEmail)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtPassword)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(58, 58, 58)
                                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(37, 37, 37)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSave)
                                        .addComponent(btnCancel))
                                .addContainerGap(21, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(windowBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(windowBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

  private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
    dispose();
  }//GEN-LAST:event_btnCancelActionPerformed

  private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
    saveRegistrar();
  }//GEN-LAST:event_btnSaveActionPerformed

  private void saveRegistrar() {
    String employeeId = FormValidationUtil.normalizeOptionalText(txtEmployeeId.getText());
    if (showValidationError(
      FormValidationUtil.validateOptionalText(
        "Employee ID",
        employeeId,
        MIN_EMPLOYEE_ID_LENGTH,
        MAX_EMPLOYEE_ID_LENGTH,
        EMPLOYEE_ID_PATTERN,
        "letters, numbers, and . _ - /"
      )
    )) {
      return;
    }

    String firstName = FormValidationUtil.normalizeOptionalText(txtFirstName.getText());
    if (showValidationError(
      FormValidationUtil.validateRequiredText(
        "First name",
        firstName,
        MIN_NAME_LENGTH,
        MAX_NAME_LENGTH,
        NAME_PATTERN,
        "letters, spaces, apostrophes, hyphens, and periods"
      )
    )) {
      return;
    }

    String lastName = FormValidationUtil.normalizeOptionalText(txtLastName.getText());
    if (showValidationError(
      FormValidationUtil.validateRequiredText(
        "Last name",
        lastName,
        MIN_NAME_LENGTH,
        MAX_NAME_LENGTH,
        NAME_PATTERN,
        "letters, spaces, apostrophes, hyphens, and periods"
      )
    )) {
      return;
    }

    String email = FormValidationUtil.normalizeOptionalText(txtEmail.getText());
    if (showValidationError(FormValidationUtil.validateRequiredEmail("Email", email, MAX_EMAIL_LENGTH))) {
      return;
    }

    String contactNumber = FormValidationUtil.normalizeOptionalText(txtContactNumber.getText());
    if (showValidationError(
      FormValidationUtil.validateOptionalText(
        "Contact number",
        contactNumber,
        MIN_CONTACT_LENGTH,
        MAX_CONTACT_LENGTH,
        CONTACT_NUMBER_PATTERN,
        "numbers, spaces, plus sign, parentheses, and hyphen"
      )
    )) {
      return;
    }

    String password = FormValidationUtil.normalizeOptionalText(new String(txtPassword.getPassword()));
    String confirmPassword = FormValidationUtil.normalizeOptionalText(new String(txtConfirmPassword.getPassword()));

    if (showValidationError(
      FormValidationUtil.validateOptionalText(
        "Password",
        password,
        MIN_PASSWORD_LENGTH,
        MAX_PASSWORD_LENGTH,
        PASSWORD_PATTERN,
        "no spaces"
      )
    )) {
      return;
    }

    if (editingRegistrar == null && password == null) {
      JOptionPane.showMessageDialog(
        this,
        "Password is required for new registrar accounts.",
        "Validation Error",
        JOptionPane.WARNING_MESSAGE
      );
      return;
    }

    if (password == null) {
      password = "";
    }
    if (confirmPassword == null) {
      confirmPassword = "";
    }

    if (!password.equals(confirmPassword)) {
      JOptionPane.showMessageDialog(
        this,
        "Password and confirm password do not match.",
        "Validation Error",
        JOptionPane.WARNING_MESSAGE
      );
      return;
    }

    if (editingRegistrar == null) {
      Registrar registrar = new Registrar()
        .setEmployeeId(employeeId)
        .setFirstName(firstName)
        .setLastName(lastName)
        .setContactNumber(contactNumber);

      Optional<Registrar> createdRegistrar = registrarService.registerRegistrar(
        email,
        password,
        registrar
      );

      if (createdRegistrar.isEmpty()) {
        JOptionPane.showMessageDialog(
          this,
          "Failed to create registrar account.",
          "Error",
          JOptionPane.ERROR_MESSAGE
        );
        return;
      }

      JOptionPane.showMessageDialog(
        this,
        "Registrar account created successfully.",
        "Success",
        JOptionPane.INFORMATION_MESSAGE
      );
    } else {
      editingRegistrar
        .setEmployeeId(employeeId)
        .setFirstName(firstName)
        .setLastName(lastName)
        .setContactNumber(contactNumber);

      boolean updated = registrarService.updateRegistrarWithEmail(
        editingRegistrar,
        email,
        password
      );

      if (!updated) {
        JOptionPane.showMessageDialog(
          this,
          "Failed to update registrar account.",
          "Error",
          JOptionPane.ERROR_MESSAGE
        );
        return;
      }

      JOptionPane.showMessageDialog(
        this,
        "Registrar account updated successfully.",
        "Success",
        JOptionPane.INFORMATION_MESSAGE
      );
    }

    if (onSavedCallback != null) {
      onSavedCallback.run();
    }

    dispose();
  }

  private boolean showValidationError(Optional<String> validationError) {
    if (validationError.isEmpty()) {
      return false;
    }

    JOptionPane.showMessageDialog(
      this,
      validationError.get(),
      "Validation Error",
      JOptionPane.WARNING_MESSAGE
    );
    return true;
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String[] args) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
      logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new RegistrarForm().setVisible(true));
  }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnCancel;
        private javax.swing.JButton btnSave;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPasswordField txtConfirmPassword;
        private javax.swing.JTextField txtContactNumber;
        private javax.swing.JTextField txtEmail;
        private javax.swing.JTextField txtEmployeeId;
        private javax.swing.JTextField txtFirstName;
        private javax.swing.JTextField txtLastName;
        private javax.swing.JPasswordField txtPassword;
        private com.group5.paul_esys.components.WindowBar windowBar1;
        // End of variables declaration//GEN-END:variables
}
