/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.group5.paul_esys.screens.registrar.cards;

import com.group5.paul_esys.modules.faculty.model.Faculty;
import java.util.function.Consumer;

/**
 *
 * @author nytri
 */
public class FacultyMemberCard extends javax.swing.JPanel {

        private Faculty faculty;
        private Consumer<Faculty> onUpdateAction;
        private Consumer<Faculty> onDeleteAction;

	/**
	 * Creates new form FacultyMemberCard
	 */
	public FacultyMemberCard() {
		initComponents();
	}

        public FacultyMemberCard(Faculty faculty, String emailAddress) {
                initComponents();
                setFacultyData(faculty, emailAddress);
        }

        public void setFacultyData(Faculty faculty, String emailAddress) {
                this.faculty = faculty;

                if (faculty == null) {
                        lblFullName.setText("Unknown Faculty");
                        lblEmail.setText(emailAddress == null || emailAddress.trim().isEmpty() ? "No email" : emailAddress.trim());
                        return;
                }

                String firstName = faculty.getFirstName() == null ? "" : faculty.getFirstName().trim();
                String lastName = faculty.getLastName() == null ? "" : faculty.getLastName().trim();
                String fullName = (lastName + ", " + firstName).replaceAll("^[,\\s]+|[,\\s]+$", "");

                lblFullName.setText(fullName.isEmpty() ? "Unknown Faculty" : fullName);
                lblEmail.setText(emailAddress == null || emailAddress.trim().isEmpty() ? "No email" : emailAddress.trim());
        }

        public void setOnUpdateAction(Consumer<Faculty> onUpdateAction) {
                this.onUpdateAction = onUpdateAction;
        }

        public void setOnDeleteAction(Consumer<Faculty> onDeleteAction) {
                this.onDeleteAction = onDeleteAction;
        }

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                lblFullName = new javax.swing.JLabel();
                lblEmail = new javax.swing.JLabel();
                btnUpdate = new javax.swing.JButton();
                btnDelete = new javax.swing.JButton();

                setBackground(new java.awt.Color(255, 255, 255));
                setBorder(new com.group5.paul_esys.ui.RoundShadowBorder());

                lblFullName.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
                lblFullName.setText("Last Name, First Name");

                lblEmail.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
                lblEmail.setForeground(new java.awt.Color(102, 102, 102));
                lblEmail.setText("lastname.firstname@vbsu.edu.ph");

                btnUpdate.setBackground(new java.awt.Color(119, 0, 0));
                btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
                btnUpdate.setText("Update");
                btnUpdate.addActionListener(this::btnUpdateActionPerformed);

                btnDelete.setBackground(new java.awt.Color(119, 0, 0));
                btnDelete.setForeground(new java.awt.Color(255, 255, 255));
                btnDelete.setText("Delete");
                btnDelete.addActionListener(this::btnDeleteActionPerformed);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblFullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnUpdate))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnDelete)))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblFullName)
                                        .addComponent(btnUpdate))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblEmail)
                                        .addComponent(btnDelete))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
                if (onUpdateAction != null && faculty != null) {
                        onUpdateAction.accept(faculty);
                }
        }//GEN-LAST:event_btnUpdateActionPerformed

        private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
                if (onDeleteAction != null && faculty != null) {
                        onDeleteAction.accept(faculty);
                }
        }//GEN-LAST:event_btnDeleteActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnDelete;
        private javax.swing.JButton btnUpdate;
        private javax.swing.JLabel lblEmail;
        private javax.swing.JLabel lblFullName;
        // End of variables declaration//GEN-END:variables
}
